version = 1

test_patterns = [
  "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/munditrade/provider-sql-crossplane"

[[analyzers]]
name = "secrets"
enabled = true
